### ISSUE TITLE
PSR-3 compliant logger is not really PSR-3 compliant

### ISSUE THREAD

**Issue by GordonGuenther** [pachico/magoo#8]
For a logger to be PSR-3 compliant it must not just implement all features of the Psr\Log\LoggerInterface, it in fact needs to contain "implements \Psr\Log\LoggerInterface", so any user of your logger can safely check that his requirements are met.

For your MagooLogger this is a bit tricky to achive, because your not only forgot the "implements \Psr\Log\LoggerInterface" but you also implemented all it's requirements with a magic __call method. So if you just add the "implements \Psr\Log\LoggerInterface" lots of fatal errors for missing implementation of abstract methods will pop up.

So, although you implemented all features of the Psr\Log\LoggerInterface in your MagooLogger, you will not be able to use it as a wrapped logger replacement in most use cases. For example in lumen you are able to configure monolog with "$app->configureMonologUsing($callback);". The callback is required to return an instance of Psr\Log\LoggerInferface, so you cannot return a MagooLogger wrapping the monolog here.

**Comment by pachico** [comment]
Thanks a lot! What you say makes all sense.
Thanks for the PR!
